server:
  port: 9000
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: GRACEFUL

spring:
  application:
    name: edge-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  config:
    import: "optional:configserver:"
  cloud:
    config:
      enabled: false
    gateway.server.webflux:
      routes:
        - id: ticket-service
          uri: ${TICKET_SERVICE_URL:http://localhost:9001}/api/flights
          predicates:
            - Path=/api/flights/**
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:9005}/api/auth/login
          predicates:
            - Path=/api/auth/**
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              replenishRate: 10
              burstCapacity: 20
              requestedTokens: 1
  data:
    redis:
      connect-timeout: 2s
      host: ${REDIS_AIRLINE_URL:localhost}
      port: 6379
      timeout: 1s
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/api/auth/.well-known/jwks.json




