gateway:
    server:
      webflux:
        routes:
          - id: auth-service
            uri: http://auth-service
            predicates:
              - Path=/api/auth/**
          - id: ticket-service
            uri: http://ticket-service
            predicates:
              - Path=/api/flights/**
          - id: booking-service
            uri: http://booking-service
            predicates:
              - Path=/bookings/**
